blueprint:
  name: SoundTouch NowPlaying Status Update for Kodi TVShow
  description: >-
    Updates SoundTouchPlus media player NowPlaying status from Kodi media player 
    TVShow content attributes when the specified SoundTouch Source is selected.
    This allows the SoundTouchPlus media player to show what is playing
    on the Kodi player when using Kodi with a SoundTouch speaker system.
  author: Todd Lucas
  domain: automation
  
  input:
    kodi_player:
      name: Kodi Media Player
      description: The Kodi media player that is playing the media.
      selector:
        entity:
          integration: kodi
          domain: media_player      
    soundtouch_player:
      name: SoundTouch Media Player
      description: The SoundTouch media player that will be updated.
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player      
    source_title:
      name: SoundTouch Source Title
      description: >-
        Source input the content item is played with (e.g. 'Product (TV)').  
        This value is case-sensitive.
      selector:
        text:
      default: "Product (TV)"

variables:
  var_kodi_player: !input kodi_player

trigger:
  # when Kodi media player media title changes.
  - platform: state
    entity_id: !input kodi_player
    attribute: media_title

condition:
  # when Kodi media player media content type is a TVShow.
  - condition: state
    entity_id: !input kodi_player
    attribute: media_content_type
    state: tvshow
  # when SoundTouchPlus source title matches input value.
  - condition: state
    entity_id: !input soundtouch_player
    attribute: source
    state: !input source_title

action:
  # call SoundTouchPlus service to set source-specific NowPlayingStatus.
  - service: soundtouchplus.update_source_nowplayingstatus
    data:
      entity_id: !input soundtouch_player
      source_title: !input source_title
      art_url: "{{ state_attr(var_kodi_player, 'entity_picture') }}"
      station_name: "{{ state_attr(var_kodi_player, 'media_series_title') }} - {{ state_attr(var_kodi_player, 'media_title') }}"
      station_location: Kodi
      
# restart the script if it is triggered again while already running.
# do not log any messages if we exceed limit threshold.
mode: restart
max_exceeded: silent  
