blueprint:
  name: SoundTouch NowPlaying Status Clear for Source
  description: >-
    Clears SoundTouchPlus source-specific NowPlaying status for the specified 
    SoundTouch Source.
  author: Todd Lucas
  domain: automation
  
  input:
    kodi_player:
      name: Kodi Media Player
      description: The Kodi media player that is playing the media.
      selector:
        entity:
          integration: kodi
          domain: media_player      
    soundtouch_player:
      name: SoundTouch Media Player
      description: The SoundTouch media player that will be updated.
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player      
    source_title:
      name: SoundTouch Source Title
      description: >-
        Source input the content item is played with (e.g. 'Product (HDMI_1)').  
        This value is case-sensitive.
      selector:
        text:
      default: "Product (TV)"

variables:
  var_kodi_player: !input kodi_player

trigger:
  # when Kodi media player media title changes to nothing.
  - platform: state
    entity_id: !input kodi_player
    attribute: media_title
    to: ''

condition:
  # when SoundTouchPlus media player source title match input value.
  - condition: state
    entity_id: !input soundtouch_player
    attribute: source
    state: !input source_title

action:
  # call SoundTouchPlus service to clear source-specific NowPlayingStatus.
  - service: soundtouchplus.clear_source_nowplayingstatus
    data:
      entity_id: !input soundtouch_player
      source_title: !input source_title

# restart the script if it is triggered again while already running.
# do not log any messages if we exceed limit threshold.
mode: restart
max_exceeded: silent  
